### PR TITLE
include check for required variables

### PR DESCRIPTION
**Pull request by danielhuppmann**
This PR adds a function to check whether required variables are included in the data.

Other miscellanous changes:
 - allow `unit` as argument for `filter()`
 - rework the `_check_rows()` function
 - rename options for `return_type` in `check_rows()` to `any` and `all`

### CODE REVIEW

**Comment by danielhuppmann** [comment]
@gidden, I changed the args vis-avis our earlier discussion, because passing over a filter as dictionary had some non-intuitive implications/results.

I may try to also implement a `iam.require_variables(df, ...)` version, too, at a later point.

**Comment by gidden** [comment]
lgtm, let's chat about the outer function before I pull.

*very* nice refactor on `check_rows()` btw =)

**Comment by danielhuppmann** [comment]
@gidden, top-level function included and unit-tested...

**Comment by gidden** [comment]
lgtm!

**Pull request merged**
