### PR TITLE
Plots

### LINKED ISSUE #21: add bar charts
initially should support years on x-axis and stacking of either regions or sector, unit on y-axis label.

### LINKED ISSUE #22: add pie chart
should be the same as bar chart but limited in one dimension (ie. only one bar)

### PR DESCRIPTION
**Pull request by gidden**
ready to merge now. closes #21 closes #22

### CODE REVIEW

**Comment by gidden** [comment]
updating CI with cartopy in just a moment

**Comment by gidden** [comment]
well that was more painful than I would have hoped..

**Comment by gidden** [comment]
ready for review @danielhuppmann

**Comment by gidden** [comment]
Should now be (finally) good to go @danielhuppmann. Yes, you are correct that currently building docs requires a file I have locally. That will be fixed when we address #20

**Comment by danielhuppmann** [comment]
looks not just good to me, but outright awesome! thanks so much @gidden!

**Pull request merged**
